name: Test python bindings

on:
#  push:
#    branches: [ "main" , "master"]
  pull_request:
    branches: [ "main" , "master"]
  workflow_dispatch:

jobs:
  python-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
      - run: bash python/build.sh
      - run: cd python/test && python -m unittest
